# Generated by Django 5.1.3 on 2024-12-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_counties',
        ),
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(null=True, to='book_outlet.country'),
        ),
    ]
